### ISSUE TITLE
Lexical or Preprocessor Issue (Xcode): 'flutter_number_to_words_english-Swifth.h' file not found

### ISSUE THREAD

**Issue by cyntiafelix** [kenguyenduc/flutter_number_to_words_english#2]
This package is great and works perfectly on Android, but when I try to build my iOS app, I get the following error:

Lexical or Preprocessor Issue (Xcode): 'flutter_number_to_words_english-Swifth.h' file not found
/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/number_to_words_english-2.0.1/ios/Classes/FlutterNumberToWordsEnglishPlugin.m:8:9: 'flutter_number_to_words_english-Swift.h' file not found

**Comment by kenguyenduc** [comment]
Thanks for the feedback ! I've updated new version. 
Please check here: https://pub.dev/packages/number_to_words_english

**Comment by kenguyenduc** [comment]
Thanks for the feedback ! I've updated new version.
Please check here: https://pub.dev/packages/number_to_words_english
